name: Upload Artifact
description: Upload artifact to S3
inputs:
  source:
    description: 'A file or directory to upload'
    required: true
  destination:
    description: 'A file or directory (must end with /) to upload to'
    required: false
outputs:
  url:
    description: 'The URL of the uploaded file or directory'
    value: ${{ steps.upload.outputs.result }}
runs:
  using: composite
  steps:
  - id: upload
    uses: actions/github-script@v6
    with:
      script: |
        const fs = require('fs');
        const path = require('path');

        const callerIdentity = await exec.exec('aws sts get-caller-identity');
        const arn = JSON.parse(callerIdentity.stdout).Arn;
        const prefix = arn.match(/\/(.+)-runner-role\//)[1];

        const source = core.getInput('source', { required: true });
        const destination = core.getInput('destination') || source;

        const sourceStats = fs.lstatSync(source);
        const destinationBasename = sourceStats.isFile() && destination.endsWith('/') ? path.basename(source) : ''
        const destinationPath = `${prefix}/${process.env.GITHUB_REPOSITORY}/${process.env.GITHUB_RUN_ID}/${process.env.GITHUB_RUN_ATTEMPT}/${destinationBasename}`
        const recursiveOption = fs.lstatSync(source).isDirectory() ? '--recursive' : '';

        const bucket = 'tf-aws-gh-runner'

        await exec.exec(`aws s3 cp ${source} s3://${bucket}/${destinationPath} ${recursiveOption} --acl public-read`)

        return `https://${bucket}/${destinationPath}`
      result-encoding: string
