version: 0.1
storage:
  s3:
    region: us-east-1
    bucket: tf-aws-gh-runner
    rootdirectory: /docker/cache/v0
  delete:
    enabled: false
  redirect:
    disable: false
  maintenance:
    uploadpurging:
      enabled: false
    readonly:
      enabled: false
http:
  secret: tf-aws-gh-runner-docker-cache-v0
health:
  storagedriver:
    enabled: false
