name: Docker Cache
description: Retrieve docker cache configuration
inputs:
  name:
    description: 'The name of the tag to use for caching docker blobs and manifests'
    required: false
outputs:
  to:
    description: 'The CSV value of the docker build --cache-to parameter'
    value: ${{ fromJSON(steps.cache.outputs.result).to }}
  from:
    description: 'The CSV value of the docker build --cache-from parameter'
    value: ${{ fromJSON(steps.cache.outputs.result).from }}
runs:
  using: composite
  steps:
  - run: |
      touch buildkitd.toml
      echo 'debug = true' >> buildkitd.toml
      echo 'insecure-entitlements = [' >> buildkitd.toml
      echo '  "network.host",' >> buildkitd.toml
      echo '  "security.insecure"' >> buildkitd.toml
      echo ']' >> buildkitd.toml
      echo '[registry."docker.io"]' >> buildkitd.toml
      echo '  mirrors = [' >> buildkitd.toml
      echo '    "internal-tf-aws-gh-runner-docker-proxy-669910242.us-east-1.elb.amazonaws.com"' >> buildkitd.toml
      echo '  ]' >> buildkitd.toml
      echo '[registry."internal-tf-aws-gh-runner-docker-proxy-669910242.us-east-1.elb.amazonaws.com"]' >> buildkitd.toml
      echo '  http = true' >> buildkitd.toml
      echo '  insecure = true' >> buildkitd.toml
    shell: bash
  - id: cache
    uses: actions/github-script@v6
    env:
      INPUTS_NAME: ${{ inputs.name }}
    with:
      script: |
        await exec.exec('docker buildx create --use --driver=docker-container --driver-opt=image=moby/buildkit:master --config=buildkitd.toml --name=buildkit');
        await exec.exec('docker buildx inspect --bootstrap')

        const name = process.env.INPUTS_NAME || process.env.GITHUB_REPOSITORY

        return {
          to: `type=s3,mode=max,prefix=docker/cache/v0/,bucket=tf-aws-gh-runner,region=us-east-1,name=${name}`,
          from: `type=s3,prefix=docker/cache/v0/,bucket=tf-aws-gh-runner,region=us-east-1,name=${name}`
        }
      result-encoding: json
