name: Docker Cache
description: Retrieve docker cache configuration
inputs:
  name:
    description: 'The name of the tag to use for caching docker blobs and manifests'
    required: false
outputs:
  to:
    description: 'The CSV value of the docker build --cache-to parameter'
    value: ${{ fromJSON(steps.cache.outputs.result).to }}
  from:
    description: 'The CSV value of the docker build --cache-from parameter'
    value: ${{ fromJSON(steps.cache.outputs.result).from }}
runs:
  using: composite
  steps:
  - run: |
      sudo echo 'debug = true' > buildkitd.toml
      sudo echo 'insecure-entitlements = [ "network.host", "security.insecure" ]' >> buildkitd.toml
      sudo echo '[registry."internal-tf-aws-gh-runner-docker-proxy-669910242.us-east-1.elb.amazonaws.com"]' >> buildkitd.toml
      sudo echo '  http = true' >> buildkitd.toml
      sudo echo '  insecure = true' >> buildkitd.toml
      cat buildkitd.toml
    shell: bash
  - id: cache
    uses: actions/github-script@v6
    env:
      INPUTS_NAME: ${{ inputs.name }}
    with:
      script: |
        await exec.exec('docker buildx create --use --driver=docker-container --driver-opt image=moby/buildkit:master --config=buildkitd.toml --name buildkit');
        await exec.exec('docker buildx install');

        const name = process.env.INPUTS_NAME || process.env.GITHUB_REPOSITORY

        return {
          to: `type=s3,mode=max,prefix=docker/cache/v0/,bucket=tf-aws-gh-runner,region=us-east-1,name=${name}`,
          from: `type=s3,prefix=docker/cache/v0/,bucket=tf-aws-gh-runner,region=us-east-1,name=${name}`
        }
      result-encoding: json
